### ISSUE TITLE
Outline code lookup tables do not show up

### ISSUE THREAD

**Issue by karateken23** [joniles/mpxj#39]
I'm trying to read the outline codes - while the outline codes are being read fine, the lookup tables are Not. I've tested this on several MPP files, and have ensured that there are lookup tables present for the outline codes.

My application is .Net, and I'm using MPXJ via IKVM.

Code is below. The outline code names show up, but the lookup table size is 0 everytime. 
I've also attached a screenshot from a MPP file - for instance, the custom fields '00:Phase' through '04: Wrong Phase' all show up in the console, but the lookup table size is 0.

Much appreciated!
![mpp_lookuptable](https://user-images.githubusercontent.com/36520224/36280902-cd4ce8c4-1269-11e8-839f-3a9fc0c0b242.png)

```
private void outlinecodereader(ProjectFile project)
{
    foreach (CustomField outlinecode in project.CustomFields)
    {
        Console.WriteLine("Outline Code Name = " + outlinecode.Alias + "; count = " + outlinecode.LookupTable.size);
    }
}
```

**Comment by joniles** [comment]
I believe this issue is fixed by the code now committed to git. There will be an MPXJ release this week which contains the fix.

**Comment by joniles** [comment]
The release is available now.

**Comment by karateken23** [comment]
Unfortunately, the outline code lookup tables still don't show up. The size is displayed as 0. 
The text custom field lookup tables are displayed correctly however. Please find attached, the MPP file I'm using.

**Comment by joniles** [comment]
Fixed in MPXJ version 7.4.1.
