### ISSUE TITLE
Primavera WBS not read or exported correctly when there is no activity under it

### ISSUE THREAD

**Issue by mewim** [joniles/mpxj#80]
I am trying to use MPXJ (Version 7.7.1) to read Primavera project from XER and XML. I found that if a WBS has no activity under it, it is going to be treated as a task. The `summary` flag will be set to `false`. Also if I try to dump the file using `PrimaveraPMFileWriter`, the WBS is going to be dumped as Activity. 

I've created a sample schedule to demonstrate this issue. The schedule is created with P6 Professional 18.8 as follows:
![screen shot 2018-12-11 at 1 24 57 pm](https://user-images.githubusercontent.com/14037726/49833652-c7c38480-fd5f-11e8-9f59-1635f504229e.png)
This is the schedule dumped as XML:
[TEST1.xml.zip](https://github.com/joniles/mpxj/files/2669665/TEST1.xml.zip)
And this is the same schedule being read and dumped from MPXJ using `PrimaveraPMFileWriter`:
[TEST1.export.xml.zip](https://github.com/joniles/mpxj/files/2669666/TEST1.export.xml.zip)

I think the cause of this issue is MPXJ only marks tasks with child tasks under it as summary task.
https://github.com/joniles/mpxj/blob/27b393e4e8421493452e9343f05932643bc0bc6c/src/main/java/net/sf/mpxj/primavera/PrimaveraReader.java#L1027

Similar issue is also found with XER file, as it is sharing `PrimaveraReader` with XML file.

Could you please look into this issue or provide a work around so that I can distinguish an empty WBS from a task? Thanks.

**Comment by joniles** [comment]
I've updated the code so that `Task.getSummary()` will only return true if the task is a WBS entry rather than an Activity, if the schedule has been read from P6, P3 or SureTrak. This separates the concept of a summary or WBS task from "a task has children". I've also provided a separate `Task.hasChildTasks()` method.

**Comment by lironzluf** [comment]
@joniles I'm still encountering this issue on P6 XER files. I'm using version `8.0.6`.
Calling `Task.getSummary()` returns `true` for WBS task but not for empty WBS task.
I'm able to identify WBS tasks using `Task.getType() == TaskType.FIXED_UNITS`, but I'm not sure this is the right way.

LMK if you need an example XER file for reproducing this issue.

**Comment by joniles** [comment]
Hello @lironzluf! I'm just doing some housekeeping and noticed your comment. I appreciate that this is more than two years old now, but do let me know if this is still and issue and if you do have an XER file example you could share that would be great. Thanks!
